name: Build for Windows

on:
  push:
    branches: [ "master" ]
    tags:
      - '*'
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Patch stormlib project
      shell: bash
      run: |
        sed 's/10.0.17134.0/10.0/g' StormLib/StormLib_vs19.vcxproj > StormLib/StormLib_vs19_.vcxproj
        rm -rf StormLib/StormLib_vs19.vcxproj
        mv StormLib/StormLib_vs19_.vcxproj StormLib/StormLib_vs19.vcxproj
        
        sed 's/10.0.17134.0/10.0/g' StormLib/StormLib_vs19_dll.vcxproj > StormLib/StormLib_vs19_dll_.vcxproj
        rm -rf StormLib/StormLib_vs19_dll.vcxproj
        mv StormLib/StormLib_vs19_dll_.vcxproj StormLib/StormLib_vs19_dll.vcxproj
        
        sed 's/10.0.17134.0/10.0/g' StormLib/StormLib_vs19_test.vcxproj > StormLib/StormLib_vs19_test_.vcxproj
        rm -rf StormLib/StormLib_vs19_test.vcxproj
        mv StormLib/StormLib_vs19_test_.vcxproj StormLib/StormLib_vs19_test.vcxproj

    - name: Build
      run: |
        cd StormLib
        msbuild StormLib_vs19.sln /property:Configuration=Release /property:Platform=x64
        cd ../CascLib
        msbuild CascLib_vs19.sln /property:Configuration=Release /property:Platform=x64

    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        name: Windows release
        tag_name: windows
        files: |
          CascLib\bin\CascLib_dll\x64\Release\CascLib.dll
          StormLib\bin\StormLib_dll\x64\Release\StormLib.dll