name: Build for Windows

on:
  push:
    branches: [ "master" ]
    tags:
      - '*'
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Patch stormlib project
      shell: bash
      run: |
        sed 's/10.0.17134.0/10.0/g' StormLib/StormLib.vcxproj > StormLib/StormLib_.vcxproj
        rm -rf StormLib/StormLib.vcxproj
        mv StormLib/StormLib_.vcxproj StormLib/StormLib.vcxproj
        
        sed 's/10.0.17134.0/10.0/g' StormLib/StormLib_dll.vcxproj > StormLib/StormLib_dll_.vcxproj
        rm -rf StormLib/StormLib_dll.vcxproj
        mv StormLib/StormLib_dll_.vcxproj StormLib/StormLib_dll.vcxproj
        
        sed 's/10.0.17134.0/10.0/g' StormLib/StormLib_test.vcxproj > StormLib/StormLib_test_.vcxproj
        rm -rf StormLib/StormLib_test.vcxproj
        mv StormLib/StormLib_test_.vcxproj StormLib/StormLib_test.vcxproj

    - name: Build
      run: |
        cd StormLib
        msbuild StormLib.sln /property:Configuration=Release /property:Platform=x64
        cd ../CascLib
        msbuild CascLib.sln /property:Configuration=Release /property:Platform=x64

    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        name: Windows release
        tag_name: windows
        files: |
          CascLib\bin\CascLib_dll\x64\Release\CascLib.dll
          StormLib\bin\StormLib_dll\x64\Release\StormLib.dll